name: Build LaTeX document
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Install TeX Live
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full

      - name: Compile LaTeX document
        run: |
          cd src
          lualatex main.tex
          lualatex main.tex

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: src/main.pdf
